Modul8
TuryNaTory/KursAkademiaAndroida pull request #11
Opened 2020-09-01 19:12 UTC by TuryNaTory

2020-09-05 11:34 UTC, keresmi requested changes
Dobra robota, napisałem kilka uwag, ale są raczej kosmetyczne.

2020-09-05 11:34 UTC, patrykserek commented on app/src/main/java/ak/www/kursakademiaandroida/features/characters/presentation/CharacterFragment.kt
> +        (activity as MainActivity).showProgressBar(enable)
Aby uniknąć takiego kastowania na `MainActivity` można taki progress bar zdefiniować w widoku samego fragmentu. Jeśli koniecznie chcesz to zrobić w ten sposób, to lepiej żeby ten fragment kodu był w bazowej klasie fragmentu, żeby nie nadpisywać go za każdym razem.

2020-09-05 11:34 UTC, patrykserek commented on app/src/main/java/ak/www/kursakademiaandroida/features/episodes/presentation/EpisodeFragment.kt
> +        (activity as MainActivity).showProgressBar(enable)
Tutaj podobnie jak pisałem wyżej.

2020-09-05 11:34 UTC, keresmi commented on app/src/main/java/ak/www/kursakademiaandroida/features/locations/presentation/LocationFragment.kt
> +        (activity as MainActivity).showProgressBar(enable)
Tutaj podobnie jak wyżej :)

2020-09-06 18:00 UTC, TuryNaTory commented on app/src/main/java/ak/www/kursakademiaandroida/features/characters/presentation/CharacterFragment.kt
> +        (activity as MainActivity).showProgressBar(enable)
Przeniosłem metodę do bazowego fragmentu. Wkradł mi się do tego pull requesta jeden commit z modułu 9, ale nie za bardzo wiem jak to teraz odkręcić.

2020-09-10 15:26 UTC, merged